[server]
# Automatically reload the app when code is saved
runOnSave = true
headless = true
enableCORS = false
port = 8501

[theme]
# Theme customization (use "light" or "dark")
base = "dark"
primaryColor = "#00ADB5"
backgroundColor = "#121212"
secondaryBackgroundColor = "#1E1E1E"
textColor = "#FFFFFF"
font = "sans serif"
