# === Zerodha API credentials ===
Zerodha_API_Key = "your_api_key_here"
Zerodha_API_Secret = "your_api_secret_here"

# === Google Sheets service account credentials ===
[gspread_service_account]
type = "service_account"
project_id = "zerodhatokensaver"
private_key_id = "2cf2b839e1b2713134a8c540af8abca201376d95"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCuQvO66ljbqUWW
yA2blNqSAgeAw8eReW52SuHnXouRB6pJUAftxroPfhM12gDiH8Z3wr0CQvEM4UpQ
8NXU7G7pyuFg1Y/I6QvhbLAQwVRrjBE6n5lIolRS4nkr3PfrruA3va2DwuGbOeyY
UbENJWUqLxU11au4muTXlZKxVmfErzbaWLYAIbSgb6DDTgWRJmgTBQwsgZ8CNlrK
28YiqA5QGUZjE7Rnb0Z+soIs3mhrYlYlfteIVrw9EaWsCMNClNCqoslCwoZNTr5h
W9PmGTHQAHxc4IOzB47qF0vM22l3heGov+NurSfWv0aOdpqoih2eDTifmOLYB5Xd
dWZA0QVhAgMBAAECggEABA8Czo2AZfo2BVJI7mf+hFVFbujSMgpbC4woYVbfGrt2
sXj8Udha/8zRhyq58m3dI/3tZ5XNN8iiY4c3jYXwbAsAAutNi0kY6QSQFXEm1Xow
Y98YEAUuh0MATEFmpe0aJwIzU23LfJhum8FdjK845M08tJ4A4rWlukIg9AUxHL6E
CJjeH9uQ9++5jYt2wDmL95hm9V3GRMkZNx0dJsaFGfoqulV5Ud0MNnHV40M+L9Ir
Q+Ybbdxd1Htv/E7OGzXKngpYR3UBK8t2gtUvUjnYPKIfdAmCb8WBENAtENmsyxZk
kI0QvtkD540kzclHQ2X9q/A32d3eLeT/QYrvWk1WyQKBgQDx9xLBDc7AhGNpJtKh
zlVujvz9l675fJ7dydkVwYWhugNloBOTmrx78f2RS3H1ENyzndL4AqNbGzldgys2
rKRLPijzrcBGy43bYr630Q5KeuQDIFqq9M/JEbgc8lDbKPK5bRVrEW3mD1/XVP7+
AtRuPdNi3Sis7zpcxJuJSbi4pQKBgQC4Xo1GBwhu0kavzMNFjL5AXuBWJEr4NIOT
l2WKhaiUlkhfakqbBtWR+YS9yQSFjKWPn2DGRIo9A8dgO3rQ6KjLq0hZ3mb30r9H
hMziChg3IbrSAYVd1aSQZJ3RPFg1KLk/8kSulqCjmh5dxAr4W73V404i0fZBL6td
n+LozisBDQKBgEJhELELk6u25frD3sbq7v78lSUQxrzE1mRr6nUQeROMD0CC8Lvu
mES8d16zvtiHPrS72FOXja8BwfQIdwNxy0SlEeD/yp7hWtJTvZR58py2J/U/nAAI
VzSG+uZeB5aIHkaGSXjs+CREFXviYm3W4uY3adVWbME8g9tNSIoaQmXNAoGAWEdN
tb4gV4/vsLWGuoKNhhznpddy3i2m4sCXKiCde6gJt0YZuukm0eJ7oLPjql6R15ck
q0qeNmDc0kMop2b/i6XT2tQW0Yrjc8cuovzaY2uPHIcF6MwnI8xJlKokQi/ho7DJ
Gh+dgziEWblI12p2FzfjbeDC3KuKjiXEbFxrUvECgYARTQJ6NbF2UErjMYWchpDm
lpFk0p3ScGoiWwfX1oLcDgTs41vgI+x/2tNYCeL6HBfwqEEk8TxcCVMFrhTTf+Fd
poYkNVi3YYK9KcDD+AbnU0NZa0ZbwJTQW+Ed20r3KUFJReNAjoP/uaOGJtoYGZYb
HaPJ/7NjllufxMMfgd3Zlg==
-----END PRIVATE KEY-----"""
client_email = "sheets-accessor@zerodhatokensaver.iam.gserviceaccount.com"
client_id = "118378016625394972635"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/sheets-accessor%40zerodhatokensaver.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
